name: Deploy Firebase Functions

on:
  push:
    branches:
      - main

jobs:
  deploy_functions:
    runs-on: ubuntu-latest
    environment: Production
    concurrency:
      group: ${{ github.workflow }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: npm install -g firebase-tools
      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'
      - run: firebase use ${{ vars.FIREBASE_PROJECT_ID }}
      - run: firebase deploy --only functions --debug
